# Generated by Django 3.2.10 on 2021-12-19 07:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partial', 'Partial'), ('completed', 'Completed')], max_length=20)),
                ('due_date', models.DateTimeField(default=datetime.date(2021, 12, 26))),
                ('reminder_interval', models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month')], default='day', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_grocerylist_created_related', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_grocerylist_updated_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grocery List',
                'db_table': 'ga_grocery_list',
                'order_with_respect_to': 'created_ts',
            },
        ),
        migrations.CreateModel(
            name='GroceryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Last Updated Date')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1.0)),
                ('unit_of_measure', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_groceryitems_created_related', to=settings.AUTH_USER_MODEL)),
                ('grocery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='grocery.grocerylist')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_groceryitems_updated_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grocery Items',
                'db_table': 'ga_grocery_items',
                'order_with_respect_to': 'created_ts',
                'unique_together': {('grocery_list', 'name')},
            },
        ),
    ]
