# Generated by Django 3.2.10 on 2021-12-19 07:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryitems',
            options={'verbose_name': 'Grocery Item'},
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 7, 13, 53, 609243)),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b6cf65cf-8cbd-45bf-aedf-ce036051d848'), primary_key=True, serialize=False),
        ),
    ]
