# Generated by Django 3.2.10 on 2021-12-19 11:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20211219_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 11, 36, 34, 965690)),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('partial', 'Partial'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
