# Generated by Django 3.2.10 on 2021-12-19 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20211219_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 13, 18, 14, 898665)),
        ),
    ]
