# Generated by Django 3.2.10 on 2021-12-20 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_grocerylist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='Grocery list 1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 27, 5, 48, 5, 678496)),
        ),
    ]
