# Generated by Django 3.2.10 on 2021-12-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20211220_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
