version: "3"

services:
  db:
    image: postgres
  dj:
    container_name: dj
    build: groceryapp
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./groceryapp:/code
    ports:
      - "80:80"
    depends_on:
      - db
